// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "recipesappclient-20181128093938--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://recipesappclient-20181128093938--hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:bfc4cac5-ff98-4f47-9c85-b12e6b8e3385",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EzrQgnLAX",
    "aws_user_pools_web_client_id": "6gr47smkarumce3ubh2m645k90",
    "aws_appsync_graphqlEndpoint": "https://esvsnz2qvjclbpm4bcpi3ncd7i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
